#!/bin/sh

# source the utilities script
. "$SNAP/bin/configuration-utilities"

# call the env_var function from the utilities script
SLIVER_DARWIN_CC_64="$(env_var)"
export SLIVER_DARWIN_CC_64

"$SNAP/bin/sliver-server" daemon
